name: release

on:
    workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get commit short SHA
        id: commit_sha
        run: echo "SHORT_SHA=$(git rev-parse --short=7 HEAD)" >> $GITHUB_ENV

      - name: Get pipeline ID
        id: pipeline_id
        run: echo "PIPELINE_ID=${{ github.run_id }}" >> $GITHUB_ENV

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Configure Flutter to use Java 17
        run: flutter config --jdk-dir="$JAVA_HOME"

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Create GitHub release and upload APK
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          RELEASE_TAG="${{ env.SHORT_SHA }}-${{ env.PIPELINE_ID }}"
          gh release create "$RELEASE_TAG" \
            --repo="$GITHUB_REPOSITORY" \
            --title="${GITHUB_REPOSITORY#*/} ${RELEASE_TAG}" \
            --generate-notes \
            build/app/outputs/flutter-apk/app-release.apk
