name: release

on:
  workflow_dispatch:

jobs:
  release:
    name: Release pushed tag
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create dummy file
        run: echo "Hello from release!" > example.txt

      - name: Create release
        env:
          GH_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          gh release create "$tag" \
            --repo="$GITHUB_REPOSITORY" \
            --title="${GITHUB_REPOSITORY#*/} ${tag#v}" \
            --generate-notes \
            example.txt
      
      